name: flick_video_player
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.

version: 0.1.0

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.8+1
  provider: ^4.0.5
  wakelock: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
