name: flick_video_player
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
repository: https://github.com/GeekyAnts/flick-video-player
homepage: https://github.com/GeekyAnts/flick-video-player

version: 0.5.0

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.0
  provider: ^6.0.1
  wakelock:
  universal_html: ^2.0.8
  dio: ^5.2.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# https://github.com/GeekyAnts/flick-video-player/issues/226
# https://github.com/creativecreatorormaybenot/wakelock/pull/213
dependency_overrides:
  wakelock:
    git:
      url: https://github.com/formigas/wakelock.git
      path: wakelock/
      ref: main
  wakelock_windows:
    git:
      url: https://github.com/formigas/wakelock.git
      path: wakelock_windows/
      ref: main